FROM python:3.7-buster

# install nginx
RUN apt-get update && apt-get install nginx vim -y --no-install-recommends
COPY nginx.default /etc/nginx/sites-available/default
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

# copy source and install dependencies
RUN mkdir -p /project_pyblog/app
RUN mkdir -p /pylog/pip_cache
RUN mkdir -p project_pyblog/pylog/
COPY requirements.txt deploy-instructions.sh /project_pyblog
COPY .pip_cache /opt/app/pip_cache/
COPY martor_demo /project_pyblog/app/
WORKDIR /project_pyblog
RUN pip install -r requirements.txt 
RUN chown -R www-data:www-data /project_pyblog

# start server
EXPOSE 80
STOPSIGNAL SIGTERM
CMD ["manage.py"]
